rwx-research/captain

internal/providers/github_provider.go

Right now, for builds triggered from pull_request events, we don't collect a commit message and we just show N/A. This is not a trivial problem to solve, because GH does everything they can to hide the commit message from us in this case (they check out a specific ref that is different than the  head commit from the PR). There are lots of things we can do to fix this, but I think the easiest immediate UX improvement is to show the PR name and PR number as the commit message. It's a bit unfortunate that this isn't a real commit message, but given how we actually use this field in the UI that won't be problematic for now.
Push test run: https://captain.build/rwx/test_suite_summaries/390a902d-5fee-4098-bb81-6983d028a682
PR test run: …

Use the PR title and number for the commit message when GHA event is pull_request

---

cmd/captain/partition.go
test/oss_integration_test.go

in line with other params, delimiter also accepts params from env
maybe we want to have this more automatic? E.g. a helper function that also sets the env var.

set delimeter from env

---

.github/workflows/continuous_delivery.yaml
.github/workflows/release_requirements.yaml
cmd/captain/partition.go
test/oss_integration_test.go
version.go

Note: As this is our first release on `releases/v1`, the diff & commit history on this PR are not complete. To see all changes from the previous release, go to https://github.com/rwx-research/captain/compare/e14a5b9...b0f3f7d9af93c66f62a2e0b6f8546b899ec7dd75
Release notes (to be published) are below:
---
- Ability to explicitly disable Cloud mode through the config file.
- Additional warning messages if Captain is misconfigured.
- A fallback to the pull-request name / number if Captain can't determine a commit message in GitHub Actions.
- Ability to manually set a "title" for a test-suite execution in Captain via `CAPTAIN_TITLE` or `--title`. This can be useful if Captain is unable to derive commit messages from your environment.
- Additional options to configure the partitioning …

Captain v1.9.11 - Release Candidate

---

internal/testingschema/v1/test.go
internal/testingschema/v1/test_test.go

When writing the upcoming markdown summary, we'll call out whether a test was flaky. This change takes retries into consideration within a single run of the CLI and informs whether the test is flaky or not.

Determine whether a v1.Test is flaky

---

cmd/captain/init.go
internal/providers/buildkite_provider.go
internal/providers/buildkite_provider_test.go
internal/providers/circleci_provider.go
internal/providers/circleci_provider_test.go
internal/providers/github_provider.go
internal/providers/github_provider_test.go
internal/providers/gitlab_ci_provider.go
internal/providers/gitlab_ci_provider_test.go
internal/providers/provider.go
internal/providers/provider_test.go

if title isn't set but commit message is, all providers falls back to commit message 
previously most providers were doing this. This PR
- ensures it happens for the generic provider
- ensures it happens late -- if the commit message is overridden somehow, the title is pulled from the latest commit message
additionally, it makes all of the provider-specific `MakeProvider` methods private

title falls back to first line of commit message

---

cmd/captain/run.go
internal/cli/interfaces.go
internal/cli/run.go
internal/reporting/configuration.go
internal/reporting/junit.go
internal/reporting/junit_test.go
internal/reporting/markdown.go
internal/reporting/markdown_test.go
internal/reporting/rwx.go
internal/reporting/text.go
internal/reporting/text_test.go
internal/targetedretries/substitution.go

Follows #13. This does the small amount of refactoring work necessary to get access to the rest of the configuration we need to make the markdown report as detailed as we'd like it to be. A follow-up PR will make the final changes to the report and enable it.
- Move the framework -> substitution mapping to targeted retries
- Add a reporting configuration to the reporters interfaces
- Pass the appropriate reporting configuration to the reporters

Thread more configuration through to the reporters

---

.captain/config.yaml
.github/workflows/continuous_integration.yaml
cmd/captain/quarantine.go
cmd/captain/run.go
internal/reporting/.snapshots/Markdown Report produces a readable summary when cloud is enabled
internal/reporting/markdown.go

This required a few bug fixes that I just lumped into this PR, but long story short:
- Uses the config file in this repo
- Fixes how the config file's reporters setting and cli flag reporters interact
- Exposes the github step summary and markdown summary reporters

Expose the new reporter options

---

cmd/captain/run.go

The changes in #16 introduced new problems with reporter configurations. `map[string]string` in Go defaults to `nil`, not an empty map 😞 Right now, if you _don't_ specify config file reporters but _do_ try to specify a reporter via CLI flag, you get a nil pointer error. 
This fixes that. I'll get tests in place ASAP (how we discussed them in Slack), but this'll fix the bug (tested by hand locally with config file only, flags only, and both).

If no reporters are set in the suite config, make a new config map

---

cmd/captain/run.go
version.go

- When fixing the interaction between the config file and flags while specifying reporters in #16, a subtle bug was introduced which caused an error when specifying reporters via CLI flag and none via config file.

Captain v1.10.1 - Release Candidate

---

cmd/captain/config.go
internal/cli/config_file.go
test/cloud_integration_test.go
test/integration_suite_test.go
test/oss_integration_test.go

Adds integration tests for the reporters both with and without a config file (that they produce files, nothing about the content since that may change version to version and is itself unit tested)

Integration test the reporters

---

go.mod
go.sum
internal/reporting/.snapshots/Markdown Report produces a readable summary when cloud is disabled
internal/reporting/.snapshots/Markdown Report produces a readable summary when cloud is enabled
internal/reporting/.snapshots/Markdown Report produces a readable summary with a custom retry template
internal/reporting/markdown.go
internal/reporting/markdown_test.go

- Ensure quarantined and canceled tests end up in the right section
- Combine message and backtrace to better handle multiline message
- Strip ANSI escape codes in the markdown summary

Fixes a few markdown summary issues

---

cmd/captain/quarantine.go
cmd/captain/run.go

With the old behavior, it was a little annoying to use `github-step-summary` in the config file because running the CLI anywhere but in GitHub Actions (e.g. locally for testing) would result in an error. With this behavior, if you're not on GitHub, we just won't try to write the summary.

No-op on github-step-summary reporter when GITHUB_STEP_SUMMARY is blank

---

.captain/config.yaml
.github/workflows/continuous_integration.yaml
go.mod
go.sum
magefile.go
test/cloud_integration_test.go
test/fixtures/integration-tests/captain-configs/junit-xml-reporter.printf-yaml
test/fixtures/integration-tests/captain-configs/markdown-summary-reporter.printf-yaml
test/fixtures/integration-tests/captain-configs/rwx-v1-json-reporter.printf-yaml
test/integration_suite_test.go
test/oss_integration_test.go

this PR
- checks for changes in the integration test suites between all releaesed versions after 1.10.2
- for each of those, runs the integration tests
- the integration tests prefix the top level description with the version
- and disable some over-constrained assertions within the tests
going forward, wrap tests or assertions you don't want included in the backwards compatibility tests in `withoutBackwardsCompatibility`, e.g.
```go
withoutBackwardsCompatibility(func() {
Expect(something).To(Equal("something-that-will-likely-change-between-versions"))
})
```

backwards compatibility testing

---

.github/workflows/continuous_integration.yaml
.github/workflows/release.yaml

Adds `workflow_call` to the release workflow so we can trigger it on merges to main, and does just that (triggers it on merges)

Release to unstable on merges to main

---

.github/workflows/release.yaml

**Fix bash shell expansion/quoting**
When migrating to the new process, I copied a lot of the existing behavior but made some tweaks. Previously, when accumulating the paths to invalidate, we were wrapping them in double quotes because we would set that string as a GitHub Actions output then use a GitHub Actions expression to interpolate them into the command (which would preserve the text as-is).
When using bash variable expansion instead, it was wrapping each of those quoted items in the string with an additional layer of single quotes (e.g. `create-invalidation --paths '"/some-path"' '"/other-path"'`) so we were trying to invalidate the literal path `"/some-path"` instead of `/some-path`.
**New aliased releases should never be the latest**
`--latest` is the default for new releases, we …

Fix a couple small release process bugs

---

.github/workflows/release.yaml

Per title. I'll manually fix `unstable`

New aliased releases that are not production are also prerelease

---

.github/workflows/release.yaml

The `if: always()` shenanigans we have to do let this slip through: https://github.com/rwx-research/captain/actions/runs/4681726108/jobs/8294710613

Ensure we do not publish if building any binaries failed

---

.github/workflows/release.yaml

Doing this has two effects:
- One, we can keep rebuilding the same SHA for testing-* and unstable-* when working on the workflow
- We have a check that does not allow re-release of published versions
- Two, draft releases don't show up in the public releases list (https://github.com/rwx-research/captain/releases)
This leaves vX.X.X, unstable, and vX as published releases.

Only production releases (and the unstable alias) are published

---

.github/workflows/release.yaml

I couldn't test this in the PR since we block the Production environment outside the main branch. Turns out with the releases not being published, the actions job needs more permission to be able to see it (makes sense).
Fixes https://github.com/rwx-research/captain/actions/runs/4682103801/jobs/8295649569#step:4:12

Give update-cloudfront more permissions

---

cmd/captain/init.go
test/fixtures/integration-tests/retries/oss-rspec-failed-not-quarantined.json
test/fixtures/integration-tests/retries/oss-rspec-quarantine.json
test/fixtures/integration-tests/retries/with-config-oss-rspec-failed-not-quarantined.json
test/fixtures/integration-tests/retry-config.yaml
test/oss_integration_test.go

OSS mode was giving this fun error when running locally:
```
Error: Invalid configuration: Unsupported runtime environment
Captain was unable to detect the presence of a supported CI provider.
To use Captain locally or on unsupported hosts, please use the --who, --branch,
and --sha flags. Alternatively, these options can also be set via the
CAPTAIN_WHO, CAPTAIN_BRANCH, and CAPTAIN_SHA environment variables.
If issues persist please reach out to support@rwx.com for assistance.
```
We only need the provider for Cloud mode, so this moves the provider validation closer to the initialization of the Cloud backend and doesn't run it in OSS mode.

 Only require a provider when we're in Cloud mode 

---

cmd/captain/config.go
cmd/captain/config_test.go
cmd/captain/init.go
cmd/captain/partition.go
internal/cli/config.go
internal/cli/partition_test.go
internal/config/config.go
internal/providers/buildkite_provider.go
internal/providers/buildkite_provider_test.go
internal/providers/circleci_provider.go
internal/providers/circleci_provider_test.go
internal/providers/gitlab_ci_provider.go
internal/providers/gitlab_ci_provider_test.go
internal/providers/provider.go
internal/providers/provider_test.go
test/cloud_integration_test.go
test/oss_integration_test.go

@tonywok let's chat to make sure these changes get into your work with `captain run` supporting partition
This PR allows `captain partition` to be run without `--index` and `--total` on CI providers that provide parallelization information
probably easiest to review this one commit-by-commit. I cleaned some things up as I was writing this (in part to understand what was going on!)

partition args can be set by provider

---

internal/runpartition/delimiter_substitution.go
internal/runpartition/delimiter_substitution_test.go
test/fixtures/integration-tests/partition-config.yaml
test/oss_integration_test.go

perhaps before we merge this: confirm there aren't weird edge cases where wrapping the test files in quotes breaks things in surprising ways
context: https://rwxhq.slack.com/archives/C04AUD3L7FU/p1681747314001059

add back shell escaping to captain run with partitioning

---

cmd/captain/init.go
cmd/captain/main.go
cmd/captain/parse.go
test/.snapshots/OSS mode Integration Tests captain parse results produces RWX JSON with the parsers
test/oss_integration_test.go

We found that this was broken. We don't want to expose this publicly, nor to we want to provide backwards compatibility guarantees, but this at least puts a small test around it (and fixes it).
- Fix the captain parse command
- Test the parse results command without backwards compatibility guarantees

Fix the hidden (not public) captain parse results command

---

cmd/captain/framework_flags.go
test/.snapshots/OSS mode Integration Tests captain run accepts the language and framework CLI flags and parses with their parser
test/oss_integration_test.go

While working on #47 I happened to stumble on this broken behavior.
```
$ ./captain parse results --language baz --framework bar  ./test/fixtures/junit.xml | jq '.framework'
{
"language": "other",
"kind": "other",
"providedLanguage": "bar",
"providedKind": "bar"
}
$ ./captain parse results --language Ruby --framework RSpec  ./test/fixtures/rspec.json
Error: Unable to parse "./test/fixtures/rspec.json" with the available parsers
```
```
$ ./captain parse results --language baz --framework bar  ./test/fixtures/junit.xml | jq '.framework'
{
"language": "other",
"kind": "other",
"providedLanguage": "baz",
"providedKind": "bar"
}
$ ./captain parse results --language Ruby --framework RSpec  ./test/fixtures/rspec.json | jq '.framework'
{
"language": "Ruby",
"kind": "RSpec"
}
```

Fix the assignment of the --framework and --language CLI flags

---

internal/providers/provider.go
internal/providers/provider_test.go

Added a bit of defensiveness to merge s.t if a provider were to omit these settings, we will still prefer the generic values.
This issue was specific to github as the github provider was relying on implicitly unset partition nodes (it does not expose parallelism in the env by default).
Go was therefore using a zero value struct to satisfy the Provider interface.
As a result, it's partition node index and total were each set to 0 -- preventing the merge code from merging in the generic provider's values.

Prefer generic provider partition settings over unset detected provider

---

internal/cli/config.go
internal/cli/config_test.go
internal/providers/provider.go
test/oss_integration_test.go

We should be able to run the same suite using either the partition command or the default run command. This determination is made by whether or we've detected the command is intending to partition or not.
This was [previously accounted for](https://github.com/rwx-research/captain/pull/43) by checking to see if the partition index and total were set to a value not equal to -1.
This was sufficient until [a patch was introduced](https://github.com/rwx-research/captain/pull/46) to fix how CAPTAIN_PARTITION_* env variables were threaded into the partition config.
That patch fixed the issue where the environment variables weren't getting picked up, however, made the approach of determining whether or not the command was running with partition insufficient. As a result, suite's configured with …

Ensure ability to run w/out partition when partition configured

---

cmd/captain/config.go
cmd/captain/run.go
internal/cli/config.go
internal/cli/config_test.go
internal/cli/run.go
internal/parsing/parse.go

Changes in this PR:
* Captain will return an error in case there are unknown fields in the YAML (**potentially breaking**)
* Captain will print a warning if
- there is a retry command, but total retries are set to 0.
- the --max-tests-to-retry option is configured, but there are no retries.
- there is a partitioning command, but the total partition count is set to 0 or 1. 
- no parser could be found using the provided framework & language values.
Some caveats:
* If the YAML parsing fails due to an unknown field, it will reference the name of the Go struct in its error message: `line 11: field retries not found in type cli.ConfigFile`. I think having the line number & field name in the error message is important, so I would not omit this. We _could_ try to filter this string, but that …

Protect against misconfiguration

---

internal/reporting/junit.go
internal/reporting/junit_test.go

Some tools rely on the file and line properties to, e.g., annotate code in a pull request. We already have this data in some cases so we might as well add it.
I tested this locally with ABQ + RSpec and it worked.

Adds file and line to the JUnit output

---

internal/targetedretries/dot_net_xunit_substitution.go
internal/targetedretries/dot_net_xunit_substitution_test.go

copy of #54 
The filter substition is directly embedded into the command, which means
that `"` quotes will behave according to the shell. Resulting in
something along the lines of:
```sh
dotnet test --filter "FullyQualifiedName=Foo.Bar(val: "Hello World")"
```
The shell will interpret this and pass an invalid string to dotnet test,
resulting in the following error:
> 2023-08-01T20:20:59.7326742Z [xUnit.net 00:00:00.24] Cmg.DataLabGateway
> .IntegrationTests: Exception filtering tests: Incorrect format for
> TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and
> try again. Note that the incorrect format can lead to no test getting
> executed.
This change will simply replace all occurrences of `"` with `\"`, which
should be interpreted by the shell correctly.

fix: escape the .net filter subsitution for shells

---

cmd/captain/config_test.go
internal/providers/generic_provider.go
internal/providers/generic_provider_test.go
test/helpers/helpers.go

Prior to this commit, `captain run` would parse the `CAPTAIN_BUILD_URL`, `CAPTAIN_TITLE`, and `CAPTAIN_COMMIT_MESSAGE` environment variables into its arguments, but those arguments would not be merged into the GenericProvider environment provided to Captain Cloud during test results updates. This diff resolves those issues.
Internal: see
https://captain.build/rwx/test_suite_summaries/84885e32-e61c-41dd-86c9-c014264b113c as an example of a manually-executed `captain run` that picks up these variables. The invocation was
```
$ cd $MINT_REPO
$ CAPTAIN_TITLE=test123 CAPTAIN_COMMIT_MESSAGE=test123message CAPTAIN_WHO=ayazhafiz CAPTAIN_BRANCH=ayaz/test-captain-env CAPTAIN_SHA=0a4e30a8bd572351d8a44cf6ece49ff4eb5d7fd9 RWX_ACCESS_TOKEN=$(cat /tmp/access-token) $(echo $CAPTAIN_REPO)/captain --debug …
```

Respect CAPTAIN_{BUILD_URL,TITLE,COMMIT_MESSAGE} variables in run

---

internal/reporting/junit.go
internal/reporting/junit_test.go

The only reporter where we _want_ color codes is the RWX report. With the contents of that report, we render messages and backtraces with color in the Captain and Mint Cloud UI.
This change adds the same ANSI color code stripping that we perform for the markdown reporter to the JUnit reporter.

Strip color codes from the junit report

---

internal/parsing/.snapshots/JavaScriptPlaywrightParser Parse parses the sample file
internal/parsing/javascript_playwright_parser.go

When trace files are available in Playwright output, add them to the output.

Add fileAttachments to test attempt meta for Playwright.

---

.github/workflows/build_and_test.yaml
.github/workflows/buildkite_agent.yaml
.github/workflows/continuous_integration.yaml
.github/workflows/release.yaml

When the tests don't run for a while, Cloud won't have the test file timings that integration tests rely on. The first run will fail as it relies on the manifest that Cloud now has, but has not yet processed into timings.
By running this weekly, Cloud will always have a fresh-enough timing to work with, and these tests should be stable and not require manual intervention (deleting manifests).

Run Build & Test CI weekly to avoid test file timings race.

---

README.md
cmd/captain/main.go
internal/backend/remote/config.go
internal/cli/update.go

~Waiting to merge this until after cut-over~.
Non-functional change. Updating error messages to point folks to cloud.rwx.com/captain and cloud.rwx.com instead of captain.build.

Replace captain.build messaging w/ cloud.rwx.com

---

internal/backend/remote/client.go
internal/backend/remote/defaults.go
internal/backend/remote/get_run_configuration_test.go
internal/backend/remote/get_test_timing_manifest_test.go
internal/backend/remote/update_test_results.go
internal/backend/remote/update_test_results_test.go
internal/reporting/.snapshots/Markdown Report produces a readable summary when cloud is enabled
internal/reporting/markdown.go
test/cloud_integration_test.go

Prior to merge, I need to make some changes to the web acl to accompany these changes.
Converting `captain.build/api` to `cloud.rwx.com/captain/api`
* Adds coverage to ensure api endpoints behave as expected when using either captain.build or any rwx cloud.
* Adds missing GetTestTimingManifest client spec

Update captain to use cloud host

---

cmd/captain/init.go
internal/parsing/.snapshots/JavaScriptCucumberJSONParser Parse parses the sample file
internal/parsing/javascript_cucumber_json_parser.go
internal/parsing/javascript_cucumber_json_parser_test.go
internal/testingschema/v1/framework.go
test/fixtures/cucumber-js.json

It's worth noting that technically they've [deprecated their JSON](https://github.com/cucumber/cucumber-js/blob/5ce371870b677fe3d1a14915dc535688946f734c/docs/formatters.md#json) format insofar as they don't intend to add new features to it.
It is however MUCH easier to parse than their [JSONL messages format](https://github.com/cucumber/cucumber-js/blob/5ce371870b677fe3d1a14915dc535688946f734c/docs/formatters.md#message) (which seems to intend for you to construct a graph of their objects as messages come through).
I named this parser w/ JSON in it to leave room for a future messages format parser, but this was really quick to add and unblock anyone interested in using Captain with cucumber-js
If anyone is hesitant to use the JSON formatter for this reason, it looks like they also support …

Add a cucumber-js parser

---

internal/parsing/.snapshots/JavaScriptCucumberJSONParser Parse parses the sample file
internal/parsing/.snapshots/RubyCucumberParser Parse parses a failing element
internal/parsing/.snapshots/RubyCucumberParser Parse parses a passing element
internal/parsing/.snapshots/RubyCucumberParser Parse parses a pending element
internal/parsing/.snapshots/RubyCucumberParser Parse parses a skipped element
internal/parsing/.snapshots/RubyCucumberParser Parse parses a undefined element
internal/parsing/.snapshots/RubyCucumberParser Parse parses an element with a failing after hook
internal/parsing/.snapshots/RubyCucumberParser Parse parses an element with a failing before hook
internal/parsing/.snapshots/RubyCucumberParser Parse parses the sample file
internal/parsing/javascript_cucumber_json_parser.go
internal/parsing/javascript_cucumber_json_parser_test.go
internal/parsing/ruby_cucumber_parser.go
internal/parsing/ruby_cucumber_parser_test.go
internal/targetedretries/.snapshots/JavaScriptCucumberSubstitution works with a real file
internal/targetedretries/.snapshots/RubyCucumberSubstitution works with a real file
internal/targetedretries/javascript_cucumber_substitution.go
internal/targetedretries/javascript_cucumber_substitution_test.go
internal/targetedretries/ruby_cucumber_substitution.go
internal/targetedretries/ruby_cucumber_substitution_test.go

Migrates the cucumber parsers from treating steps as tests and hooks as errors to simply calling a scenario a test. @TAGraves and I think this aligns better with the cucumber model and it seems like it is how retries would need to function (you can't retry only part of a scenario)

Make scenarios the test, not steps

---

.mint/ci.yaml
.mint/publish.yaml
.mint/release.yaml
.mint/test_backwards_compatibility.yaml

I didn't test this earlier as I didn't want to create random releases.
Note that the latest v1.13.2 release is now technically pointing at a commit in this branch. I don't know if this has any implications when this branch will be deleted.

Fix publishing workflow

---

internal/cli/run.go

In OSS mode, we should avoid writing to `MINT_LINKS` because those results won't be available in Captain Cloud.

Only write to MINT_LINKS when cloud is enabled

---

.mint/ci.yaml
cmd/captain/init.go
internal/parsing/.snapshots/JavaScriptVitestParser Parse parses the sample file
internal/parsing/javascript_vitest_parser.go
internal/parsing/javascript_vitest_parser_test.go
internal/testingschema/v1/framework.go
test/fixtures/vitest.json

This change adds support for Vitest. 
Notably, this is _nearly_ the same as the Jest one (just with a few fields missing). Unfortunately, that means it makes it super challenging to tell if a file we're parsing is Jest or Vitest. We need to parse Jest _first_ in case it's Jest. If it is, the Vitest parser likely can parse it, but we'll prefer the first parser we find.

Add support for vitest

---

internal/targetedretries/.snapshots/JavaScriptVitestSubstitution works with a real file
internal/targetedretries/javascript_vitest_substitution.go
internal/targetedretries/javascript_vitest_substitution_test.go
internal/targetedretries/substitution.go

I neglected to add this in #77 because I haven't added a new framework in a bit!
With this change, those using Captain with Vitest can use Captain's retries as well.

Support targeted retries for Vitest

---

.mint/ci.yaml
internal/parsing/.snapshots/RubyMinitestParser Parse parses the sample file
internal/parsing/ruby_minitest_parser.go
internal/targetedretries/.snapshots/RubyMinitestSubstitution works with a real file for Rails
internal/targetedretries/.snapshots/RubyMinitestSubstitution works with a real file for non-Rails
test/fixtures/minitest.xml

When failure messages are multiline in minitest, the minitest-reporters gem truncates the `message` field to the first line followed by `...`.
Within the contents field of the failure/error, we actually have all lines so we should use those lines instead.

Improve the quality of the error message for minitest

---

internal/parsing/javascript_vitest_parser.go
internal/parsing/javascript_vitest_parser_test.go

Vitest v2.1.1 appears to be using floats instead of ints for some of the times and durations. This code previously expected ints, but I've updated to float64 so it can parse both now.

Fix vitest parsing of times and durations

---

go.mod
go.sum
internal/fs/local.go
internal/fs/local_test.go

A bug was reported where Captain was returning an error (`Failed to assemble run command: unable to expand filepath glob: syntax error in pattern`) given a very simple glob pattern against the `test` directory: `test/**/*_test.rb`. 
It turns out that the test directory contained a file which had characters in the name that were special to `filepath.Glob`. The library we were using to support doublestar globs was abandoned and did not properly handle escaping these (there's a PR up for it here: https://github.com/yargevad/filepathx/pull/5).
This PR moves us to https://github.com/bmatcuk/doublestar, a much more popular and maintained library for this.

Replace the abandoned filepathx library with doublestar; ensure glob characters in paths do not break globbing

---

cmd/captain/run.go
internal/cli/config_file.go
test/fixtures/integration-tests/captain-configs/junit-xml-reporter.printf-yaml
test/fixtures/integration-tests/captain-configs/markdown-summary-reporter.printf-yaml
test/fixtures/integration-tests/captain-configs/rwx-v1-json-reporter.printf-yaml

The field was previously missing a YAML annotation, thus Go's YAML decoder expected the name to be `maxtests`, instead of the documented `max-tests`. 
This was reported in #85

Fix parsing `max-tests` option

---

internal/cli/config.go

Now that you can use a retry command even when retries are disabled, this warning isn't necessary.
It's a little unfortunate that if you aren't taking advantage of "Retry failed tests" and you have a retry command configured but no retries, you won't get a notice that retries are disabled -- but at the same time, I think that is discoverable in other ways.

Removes the warning about a configured retry command with no retries

---

internal/cli/run.go

Without this, we might exit 0 even when there are test failures. 
I considered some other options for fixing this, but they're all breaking changes that might cause existing test suites to start failing. Ideally we would have a check at the end of execution to see if we have test failures or other errors and exit with a nonzero exit code, but today we just rely on the initial command's exit code being nonzero. Since a Mint retry doesn't have n initial command, we had no nonzero exit code to fall back on.

Initialize the run error when doing a failed tests retry

---

internal/backend/local/client.go
internal/backend/local/client_test.go
internal/backend/remote/update_test_results.go
internal/backend/remote/update_test_results_test.go
internal/backend/types.go
internal/cli/run.go
internal/cli/run_test.go
internal/cli/update.go
internal/mocks/backend.go

When test results are >= 5MB, we'll clear our derivedFrom since this is just ancillary data used for debugging.

Remove derivedFrom data when it is too big

---

internal/cli/run.go
internal/reporting/text.go

We felt things were a little unclear when we used the merged results.

Only use the new test results when writing the output summary

---

internal/fs/local.go
internal/fs/local_test.go

This adds support for starting a partition glob with `!`, which will cause it to _negate_ the files matched -- i.e., if the file would otherwise be included, it is instead excluded. Globs are applied in the order they are specified, and the last matching glob wins for each particular file (i.e., if the last glob that matches is negative, the file will not be included; if the last glob is positive, it will be included).

Support negative globs for partition globs

---

cmd/captain/config.go

With this change, captain will accept both `config.yaml` and `config.yml`. 
If both files are present, it will fail with the following error:
```
Error: Invalid configuration: Unable to identify configuration file
Captain found multiple configuration files in your environment:
/Users/foo/.captain/config.yaml,
/Users/foo/.captain/config.yml
Please make sure only one config file is present in your environment or
explicitly specify one using the '--config-file' flag.
```
Note that this doesn't apply to `flakes.yaml`, `quarantines.yaml`, and `timings.yaml` - we continue to expect the four-letter `yaml` extension for these files. This should be fine since they are not supplied by the user - instead these are artifacts of captain itself.

Accept `yml` as a possible file extension for the config file

---

.mint/test.yaml
cmd/captain/config.go

It hadn't occurred to me that we can run captain without a config file. The previous PR (#93) introduced a panic when captain was called without one. 
I've added a test in Mint to check that we can still run Captain without the need of a config file.

Re-apply "Accept `yml` as possible config file extension" with added bug-fix

---

internal/testingschema/v1/test.go

I think we need a broader fix to how we are handling scope comparisons, but this will fix an issue with Playwright tests when using "retry failed tests" from Mint.

Treat nil and empty string as equal when comparing scopes during merge

---

internal/parsing/javascript_jest_parser.go
internal/parsing/javascript_jest_parser_test.go
internal/parsing/javascript_vitest_parser.go
internal/parsing/javascript_vitest_parser_test.go

We found that other errors had a pretty disappointing DX since it simply says something like "Test suite had no tests" without any information about which suite (_unless_ we grab this field)

Track the name of other errors in jest and vitest as the file location

---

cmd/captain/parse.go
internal/cli/parse.go
internal/errors/errors.go
internal/parsing/parse.go

Don't swallow error messages when failing due to duplicate test IDs

---

.mint/publish.yml

This failed during the last release. It looks like the work was done to update to 2.0.0 but we did not in fact update to 2.0.0

Update to aws/assume-role 2.0.0

---

internal/parsing/parse.go
internal/testingschema/v1/test.go
internal/testingschema/v1/test_test.go

Rather than doing a nearly-quadratic check for matching identities, this constructs a string based on the factors previously used to check for matches and adds that to a map.
```
v1.17.3
$ time $(captain parse results ~/Downloads/rspec.json > /dev/null)
real	0m3.656s
user	0m3.848s
sys	0m0.231s
v1.18.1
$ time $(captain parse results ~/Downloads/rspec.json > /dev/null)
real	0m28.469s
user	0m28.460s
sys	0m0.313s
this version:
$ time $(captain parse results ~/Downloads/rspec.json > /dev/null)
real	0m3.408s
user	0m3.349s
sys	0m0.266s
```

Improve the performance of the duplicate test matching

---

internal/parsing/.snapshots/RubyCucumberParser Parse parses a skipped element
internal/parsing/.snapshots/RubyCucumberParser Parse parses an element with a failing after hook
internal/parsing/.snapshots/RubyCucumberParser Parse parses an element with a failing before hook
internal/parsing/.snapshots/RubyCucumberParser Parse parses the sample file
internal/parsing/.snapshots/RubyCucumberParser Parse parses the sample file that uses background
internal/parsing/ruby_cucumber_parser.go
internal/parsing/ruby_cucumber_parser_test.go
test/fixtures/cucumber/background_integration.json

A feature can hoist up shared steps into a Background shared across all Scenarios.
From the cucumber json they are a top-level element. This results in creating duplicate rwx tests.
Instead, when we come across a Background, prepend its properties into the subsequent Scenario. This seems to indeed be how the [ruby json formatter works](https://github.com/cucumber/cucumber-ruby/blob/main/spec/cucumber/formatter/json_spec.rb#L454-L524). 
While in here noticed that we're not properly handling after hooks.
---
I took a look at the Javascript Cucumber parser to see if it had the same issue, but at least experimentally it seems to produce json with the Background already combined into the Scenario.

Fix handling of Cucumber background declaration

---

.mint/buildkite.yml
.mint/ci.yml
.mint/generate-backwards-compatibility-tests.yml
.mint/lint.yml
.mint/publish.yml
.mint/release.yml
.mint/test-backwards-compatibility.yml
.mint/test.yml
.mint/upload.yml
internal/cli/partition.go
internal/cli/partition_test.go
internal/testing/test_partition.go
internal/testing/test_partition_test.go

Targeting total runtime / partitions for bin capacity can lead to many scenarios where you have empty bins. This is not ideal for test partitioning because we want to distribute the tests across a specified number of workers as evenly as possible. Notably, we _don't_ want to try to fill bins as full as possible leaving any empty. 
Instead of bin packing, this problem more closely relates to load balancing. A simple "shortest queue first" approach works very well and ensures all partitions get tests (so long as there are more files than partitions). In this case, queue depth is the total runtime we've added so far.

Load balance the test file timings across N workers instead of applying a bin packing algorithm

---

.mint/release.yml

I missed these since they don't run on pull requests

Add missed base configuration in dynamic embedded runs

---

internal/cli/run_command.go

You might want to pass through additional flags like `--debug` or `--runInBand` even when using your partition command. This adds support for that.

Allow passing through additional args even when partitioning

---

README.md

I noticed these icons weren't rendering correctly anymore. I don't know why but it seems like the newlines were messing it up.

Fix the icons in the readme

---

internal/cli/run.go
internal/mint/retry_actions.go

Tested in mint using a pre-release.
Also, simulated mint locally using:
```
MINT="true" MINT_ACTOR="tony" MINT_RUN_URL="fake" MINT_TASK_URL="fake" MINT_RUN_ID="fake" MINT_TASK_ID="fake" MINT_TASK_ATTEMPT_NUMBER="fake" MINT_RUN_TITLE="fake" MINT_GIT_REPOSITORY_URL="fake" MINT_GIT_REPOSITORY_NAME="fake" MINT_GIT_COMMIT_MESSAGE="fake" MINT_GIT_COMMIT_SHA="fake" MINT_GIT_REF="fake" MINT_GIT_REF_NAME="fake" MINT_RETRY_ACTIONS="./tmp/mint-retry-actions" MINT_ERRORS="./tmp/mint-errors" MINT_TIPS="./tmp/tips" captain run fake-suite
```
---
Previously we would always make a mint retry action, even if we knew we couldn't successfully retry.
This would then cause UI to show the option to retry failures even though clicking it would always fail.
Instead, have captain produce a custom tip informing …

Produce custom mint tip informing user of missing retry command

---

cmd/captain/partition.go
cmd/captain/run.go
internal/cli/config.go
internal/cli/config_file.go
internal/cli/partition.go
internal/cli/partition_test.go

Playwright configures a `testDir` and reports test results relative to the test dir. As a result, Captain records test results relative to this `testDir`.
When this happens, comparison with historical timing data will fail, falling back to round-robin.
This is because the server file ends up relative to the `testDir`, whereas captain's glob is the file on disk.
Supplying this new option allows users to augment the client test file path for the sole purpose of matching in scenarios like playwright (and potentially others).
https://github.com/user-attachments/assets/f3b3fbf9-2e84-4227-89cf-7755931547c8
```
% ../../rwx/captain/captain partition trimtest --index 0 --total 2 tests/**/*
WARN	No test file timings were matched. Using naive round-robin strategy.
tests/example.spec.js …
```

Add trim prefix to partition config

---

internal/reporting/text.go
internal/reporting/text_test.go
test/.snapshots/OSS mode Integration Tests captain merge parses and merges provided results
test/.snapshots/OSS mode Integration Tests captain merge supports globs

Failed, timed out, and canceled tests are output as a list of test names, one per line. Other tests are included only in the counts at the end of the output.

Only output counts for tests with non-failure status.

---

internal/cli/.snapshots/Merge when given multiple globs globs each pattern and merges the results
internal/parsing/.snapshots/DotNetxUnitParser Parse parses the sample file
internal/parsing/.snapshots/GoTestParser Parse parses the sample file
internal/parsing/.snapshots/JavaScriptKarmaParser Parse parses the sample file
internal/parsing/.snapshots/JavaScriptKarmaParser Parse puts a generic other error in place when there are no errors but the suite failed
internal/parsing/.snapshots/JavaScriptPlaywrightParser Parse parses the sample file
internal/parsing/.snapshots/JavaScriptPlaywrightParser Parse parses the sample file with an error in global setup
internal/parsing/.snapshots/JavaScriptPlaywrightParser Parse parses the sample file with other errors
internal/testingschema/v1/test.go

See https://github.com/rwx-research/captain/pull/98; this is needed to ensure test matching can work correctly when retrying failed tests onto a new node.

Preserve the Scope field in RWX test results

---

internal/cli/run.go
internal/cli/run_test.go
test/.snapshots/OSS mode Integration Tests captain run accepts the language and framework CLI flags and parses with their parser

When using "Retry failed tests" with intermediate artifacts, we were not setting the correct retry ID. If two attempts have occurred and then we retry failed tests, the next attempt should use a retry ID of 3, but previously it would've used 1.

Track the previous retry ID and use it for the artifact storage retry ID

---

internal/backend/local/client.go
internal/backend/local/client_test.go
internal/backend/remote/client.go
internal/backend/remote/get_quarantined_tests_test.go
internal/backend/types.go
internal/cli/run.go
internal/cli/run_test.go
internal/mocks/backend.go

If a failure/flake on main gets quarantined, there might be a lot of slow test suite runs started before the quarantine that will be affected by it. This pulls the quarantined tests just in time so that we use the most up to date data when quarantining tests.

Refetch quarantined tests right before using them

---

internal/backend/local/client.go
internal/backend/local/client_test.go
internal/backend/remote/update_test_results.go
internal/backend/remote/update_test_results_test.go
internal/backend/types.go
internal/cli/run.go
internal/cli/run_test.go
internal/cli/update.go
internal/mocks/backend.go

Note this bumps the default threshold from 5 MiB to 25 MiB.

Strip backtraces from test attempt data if results file is too large

---

internal/cli/run_test.go
internal/parsing/.snapshots/JavaScriptPlaywrightParser Parse parses the sample file
internal/parsing/go_ginkgo_parser.go
internal/parsing/javascript_playwright_parser.go
internal/reporting/markdown_test.go
internal/targetedretries/dot_net_xunit_substitution_test.go
internal/targetedretries/elixir_exunit_substitution_test.go
internal/targetedretries/go_ginkgo_substitution_test.go
internal/targetedretries/go_test_substitution_test.go
internal/targetedretries/javascript_cucumber_substitution_test.go
internal/targetedretries/javascript_cypress_substitution_test.go
internal/targetedretries/javascript_jest_substitution_test.go
internal/targetedretries/javascript_mocha_substitution_test.go
internal/targetedretries/javascript_playwright_substitution_test.go
internal/targetedretries/javascript_vitest_substitution_test.go
internal/targetedretries/json_substitution_test.go
internal/targetedretries/phpunit_substitution_test.go
internal/targetedretries/python_pytest_substitution_test.go
internal/targetedretries/python_unittest_substitution_test.go
internal/targetedretries/ruby_cucumber_substitution_test.go
internal/targetedretries/ruby_minitest_substitution_test.go
internal/targetedretries/ruby_rspec_substitution_test.go
internal/testingschema/v1/summary_test.go
internal/testingschema/v1/test.go
internal/testingschema/v1/test_test.go

In Playwright, timedOut tests have messages just like failed tests.
The most interesting changes here are in `internal/parsing/javascript_playwright_parser.go` and the snapshot for that file's tests.

Allow messages, exceptions, and backtraces for timed out tests in Playwright

---

internal/backend/remote/update_test_results.go
internal/cli/parse.go
internal/testingschema/v1/strip.go

Now you can set `CAPTAIN_STRIP_DERIVED_FROM` and `CAPTAIN_MAX_FILE_SIZE_IN_MEGABYTES` when running `captain parse results` to limit the size and noise of the output results.

Adds environment variables for stripping data from captain parse results

---

internal/parsing/javascript_mocha_parser.go

These fields can be more than just a string. Since we don't actually use them, I chose to remove them from the parser.

Make the Mocha error parser more generous
